Switch to a simpler method, fix stuff

diff --git a/oxidizr-arch b/oxidizr-arch
--- a/oxidizr-arch
+++ b/oxidizr-arch
@@ -1,27 +1,25 @@
 #!/usr/bin/bash
 
-cd "$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )"
+cd "$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )" || exit
 
 C_RED='\e[38;5;9m'
 C_INVERT='\e[7m'
 C_RESET='\e[0m'
 
+BIN_PATH=/usr/bin
 FLAG_DIR=/usr/share/oxidizr-arch
 
 ## COREUTILS
 
-BIN_PATH=/usr/bin
-CU_CORE_DIR=cu-core
-UU_CORE_DIR=uu-core
-SWITCHER_CORE_DIR=au-core
+UU_CORE_PREF=uu
 CU_CORE_PREF=cu
 
 uutils-core () {
     echo UU-CORE
 
-    [ ! -d ${BIN_PATH}/${SWITCHER_CORE_DIR} ] && echo -e "${C_RED}ERROR: Not set up${C_RESET}" >&2 && exit 1
+    [ ! -f ${BIN_PATH}/${CU_CORE_PREF}-ls ] && echo -e "${C_RED}ERROR: Not set up${C_RESET}" >&2 && exit 1
 
-    ln -sfT ${BIN_PATH}/${UU_CORE_DIR}/ ${BIN_PATH}/${SWITCHER_CORE_DIR} || exit 1
+    cat ${FLAG_DIR}/lists/cu-core-files-move | xargs -I@ uu-cp -p ${BIN_PATH}/${UU_CORE_PREF}-@ ${BIN_PATH}/@
 
     touch ${FLAG_DIR}/core-on
 }
@@ -29,9 +27,9 @@ uutils-core () {
 coreutils-core () {
     echo CU-CORE
 
-    [ ! -d ${BIN_PATH}/${SWITCHER_CORE_DIR} ] && echo -e "${C_RED}ERROR: Not set up${C_RESET}" >&2 && exit 1
+    [ ! -f ${BIN_PATH}/${CU_CORE_PREF}-ls ] && echo -e "${C_RED}ERROR: Not set up${C_RESET}" >&2 && exit 1
 
-    ln -sfT ${BIN_PATH}/${CU_CORE_DIR}/ ${BIN_PATH}/${SWITCHER_CORE_DIR} || exit 1
+    cat ${FLAG_DIR}/lists/cu-core-files-move | xargs -I@ uu-cp -p ${BIN_PATH}/${CU_CORE_PREF}-@ ${BIN_PATH}/@
 
     rm ${FLAG_DIR}/core-on
 }
@@ -39,59 +37,25 @@ coreutils-core () {
 setup-core () {
     echo SETUP-CORE
 
+    [ -f ${BIN_PATH}/${CU_CORE_PREF}-ls ] && echo -e "${C_RED}ERROR: Already set up${C_RESET}" >&2 && exit 1
     pacman -Qi uutils-coreutils &> /dev/null || { echo "uutils-coreutils not installed"; exit 0; }
 
-    mkdir ${BIN_PATH}/${CU_CORE_DIR} || exit 1
-    mkdir ${BIN_PATH}/${UU_CORE_DIR} || exit 1
-
-    # copy coreutils that have a uutils replacement -> cu-core/
-    cat ${FLAG_DIR}/lists/cu-core-files-move | xargs -L1 basename | xargs -I@ cp -p ${BIN_PATH}/@ ${BIN_PATH}/${CU_CORE_DIR}
-    echo SETUP-CORE1
-
-    # copy uutils that replace -> uu-core/
-    cat ${FLAG_DIR}/lists/cu-core-files-move | xargs -L1 basename | xargs -I@ ln -s ${BIN_PATH}/uu-coreutils ${BIN_PATH}/${UU_CORE_DIR}/@
-    echo SETUP-CORE2
-
-    # link new uutils -> uu-core/uu-coreutils
-    cat ${FLAG_DIR}/lists/uu-core-files-new-nopref | xargs -L1 basename | xargs -I@ ln -s ${BIN_PATH}/uu-coreutils ${BIN_PATH}/@
-    echo SETUP-CORE3
-
-    # make the switcher link (by default set to coreutils)
-    ln -s ${BIN_PATH}/${CU_CORE_DIR} ${BIN_PATH}/${SWITCHER_CORE_DIR}
-    echo SETUP-CORE4
-
-    # link util_x -> au-core/util_x
-    cat ${FLAG_DIR}/lists/cu-core-files-move | xargs -L1 basename | xargs -I@ ln -sf ${BIN_PATH}/${SWITCHER_CORE_DIR}/@ ${BIN_PATH}/@
-    echo SETUP-CORE5
-
-    # make prefix links to coreutils so that they are still usable
-    cat ${FLAG_DIR}/lists/cu-core-files-move | xargs -L1 basename | xargs -I@ ln -s ${BIN_PATH}/${CU_CORE_DIR}/@ ${BIN_PATH}/${CU_CORE_PREF}-@
-    echo SETUP-CORE6
+    cat ${FLAG_DIR}/lists/cu-core-files-move | xargs -I@ uu-cp -p ${BIN_PATH}/@ ${BIN_PATH}/${CU_CORE_PREF}-@
 
     touch ${FLAG_DIR}/core-setup
 
     [ -f ${FLAG_DIR}/core-on ] && uutils-core
-    echo SETUP-CORE7
+
+    exit 0
 }
 
 remove-core () {
     echo REMOVE-CORE
 
-    [ ! -d ${BIN_PATH}/${SWITCHER_CORE_DIR} ] && echo -e "${C_RED}ERROR: Not set up${C_RESET}" >&2 && exit 1
+    [ ! -f ${BIN_PATH}/${CU_CORE_PREF}-ls ] && echo -e "${C_RED}ERROR: Not set up${C_RESET}" >&2 && exit 1
 
-    # restore coreutils
-    cat ${FLAG_DIR}/lists/cu-core-files-move | xargs -L1 basename | xargs -I@ cp -p --remove-destination ${BIN_PATH}/${CU_CORE_DIR}/@ ${BIN_PATH}/
-    rm -fr ${BIN_PATH}/${CU_CORE_DIR}
-
-    # remove uutils noprefix links
-    cat ${FLAG_DIR}/lists/uu-core-files-new-nopref | xargs -L1 basename | xargs -I@ rm ${BIN_PATH}/@
-    rm -fr ${BIN_PATH}/${UU_CORE_DIR}
-
-    # remove coreutils prefix links
-    cat ${FLAG_DIR}/lists/cu-core-files-move | xargs -L1 basename | xargs -I@ rm ${BIN_PATH}/${CU_CORE_PREF}-@
-
-    # remove switcher
-    rm -d ${BIN_PATH}/${SWITCHER_CORE_DIR}
+    cat ${FLAG_DIR}/lists/cu-core-files-move | xargs -I@ uu-cp -p ${BIN_PATH}/${CU_CORE_PREF}-@ ${BIN_PATH}/@
+    cat ${FLAG_DIR}/lists/cu-core-files-move | xargs -I@ rm ${BIN_PATH}/${CU_CORE_PREF}-@
 
     rm ${FLAG_DIR}/core-setup
 }
@@ -111,17 +75,15 @@ post-transaction-core () {
 
 ## FINDUTILS
 
-CU_FIND_DIR=cu-fnd
-UU_FIND_DIR=uu-fnd
-SWITCHER_FIND_DIR=au-fnd
+UU_FIND_PREF=uu
 CU_FIND_PREF=cu
 
 uutils-find () {
     echo UU-FIND
 
-    [ ! -d ${BIN_PATH}/${SWITCHER_FIND_DIR} ] && echo -e "${C_RED}ERROR: Not set up${C_RESET}" >&2 && exit 1
+    [ ! -f ${BIN_PATH}/${CU_FIND_PREF}-find ] && echo -e "${C_RED}ERROR: Not set up${C_RESET}" >&2 && exit 1
 
-    ln -sfT ${BIN_PATH}/${UU_FIND_DIR}/ ${BIN_PATH}/${SWITCHER_FIND_DIR} || exit 1
+    cat ${FLAG_DIR}/lists/cu-find-files-move | uu-xargs -I@ cp -p ${BIN_PATH}/${UU_FIND_PREF}-@ ${BIN_PATH}/@
 
     touch ${FLAG_DIR}/find-on
 }
@@ -129,9 +91,9 @@ uutils-find () {
 coreutils-find () {
     echo CU-FIND
 
-    [ ! -d ${BIN_PATH}/${SWITCHER_FIND_DIR} ] && echo -e "${C_RED}ERROR: Not set up${C_RESET}" >&2 && exit 1
+    [ ! -f ${BIN_PATH}/${CU_FIND_PREF}-find ] && echo -e "${C_RED}ERROR: Not set up${C_RESET}" >&2 && exit 1
 
-    ln -sfT ${BIN_PATH}/${CU_FIND_DIR}/ ${BIN_PATH}/${SWITCHER_FIND_DIR} || exit 1
+    cat ${FLAG_DIR}/lists/cu-find-files-move | uu-xargs -I@ cp -p ${BIN_PATH}/${CU_FIND_PREF}-@ ${BIN_PATH}/@
 
     rm ${FLAG_DIR}/find-on
 }
@@ -139,48 +101,25 @@ coreutils-find () {
 setup-find () {
     echo SETUP-FIND
 
+    [ -f ${BIN_PATH}/${CU_FIND_PREF}-find ] && echo -e "${C_RED}ERROR: Already set up${C_RESET}" >&2 && exit 1
     pacman -Qi uutils-coreutils &> /dev/null || { echo "uutils-findutils not installed"; exit 0; }
 
-    mkdir ${BIN_PATH}/${CU_FIND_DIR} || exit 1
-    mkdir ${BIN_PATH}/${UU_FIND_DIR} || exit 1
-
-    # copy coreutils that have a uutils replacement -> cu-find/
-    cat ${FLAG_DIR}/lists/cu-find-files-move | xargs -L1 basename | xargs -I@ cp -p ${BIN_PATH}/@ ${BIN_PATH}/${CU_FIND_DIR}
-
-    # copy uutils that replace -> uu-find/
-    cat ${FLAG_DIR}/lists/cu-find-files-move | xargs -L1 basename | xargs -I@ ln -s ${BIN_PATH}/uu-@ ${BIN_PATH}/${UU_FIND_DIR}/@
-
-    # make the switcher link (by default set to coreutils)
-    ln -s ${BIN_PATH}/${CU_FIND_DIR} ${BIN_PATH}/${SWITCHER_FIND_DIR}
-
-    # link util_x -> au-core/util_x
-    cat ${FLAG_DIR}/lists/cu-find-files-move | xargs -L1 basename | xargs -I@ ln -sf ${BIN_PATH}/${SWITCHER_FIND_DIR}/@ ${BIN_PATH}/@
-
-    # make prefix links to coreutils so that they are still usable
-    cat ${FLAG_DIR}/lists/cu-find-files-move | xargs -L1 basename | xargs -I@ ln -s ${BIN_PATH}/${CU_FIND_DIR}/@ ${BIN_PATH}/${CU_FIND_PREF}-@
+    cat ${FLAG_DIR}/lists/cu-find-files-move | uu-xargs -I@ cp -p ${BIN_PATH}/@ ${BIN_PATH}/${CU_FIND_PREF}-@
 
     touch ${FLAG_DIR}/find-setup
 
     [ -f ${FLAG_DIR}/find-on ] && uutils-find
+
+    exit 0
 }
 
 remove-find () {
     echo REMOVE-FIND
 
-    [ ! -d ${BIN_PATH}/${SWITCHER_FIND_DIR} ] && echo -e "${C_RED}ERROR: Not set up${C_RESET}" >&2 && exit 1
+    [ ! -f ${BIN_PATH}/${CU_FIND_PREF}-find ] && echo -e "${C_RED}ERROR: Not set up${C_RESET}" >&2 && exit 1
 
-    # restore coreutils
-    cat ${FLAG_DIR}/lists/cu-find-files-move | xargs -L1 basename | xargs -I@ cp -p --remove-destination ${BIN_PATH}/${CU_FIND_DIR}/@ ${BIN_PATH}/
-    rm -fr ${BIN_PATH}/${CU_FIND_DIR}
-
-    # remove uutils noprefix links
-    rm -fr ${BIN_PATH}/${UU_FIND_DIR}
-
-    # remove coreutils prefix links
-    cat ${FLAG_DIR}/lists/cu-find-files-move | xargs -L1 basename | xargs -I@ rm ${BIN_PATH}/${CU_FIND_PREF}-@
-
-    # remove switcher
-    rm -d ${BIN_PATH}/${SWITCHER_FIND_DIR}
+    cat ${FLAG_DIR}/lists/cu-find-files-move | uu-xargs -I@ cp -p ${BIN_PATH}/${CU_FIND_PREF}-@ ${BIN_PATH}/@
+    cat ${FLAG_DIR}/lists/cu-find-files-move | uu-xargs -I@ rm ${BIN_PATH}/${CU_FIND_PREF}-@
 
     rm ${FLAG_DIR}/find-setup
 }
@@ -200,6 +139,7 @@ post-transaction-find () {
 
 ## SUDO
 
+RS_SUDO_SUF=rs
 VN_SUDO_SUF=vn
 
 rust-sudo () {
@@ -207,9 +147,9 @@ rust-sudo () {
 
     [ ! -f ${BIN_PATH}/su-${VN_SUDO_SUF} ] && echo -e "${C_RED}ERROR: Not set up${C_RESET}" >&2 && exit 1
 
-    ln -sfT ${BIN_PATH}/su-rs ${BIN_PATH}/su || exit 1
-    ln -sfT ${BIN_PATH}/sudo-rs ${BIN_PATH}/sudo || exit 1
-    ln -sfT ${BIN_PATH}/visudo-rs ${BIN_PATH}/visudo || exit 1
+    cp -p ${BIN_PATH}/su-${RS_SUDO_SUF} ${BIN_PATH}/su || exit 1
+    cp -p ${BIN_PATH}/sudo-${RS_SUDO_SUF} ${BIN_PATH}/sudo || exit 1
+    cp -p ${BIN_PATH}/visudo-${RS_SUDO_SUF} ${BIN_PATH}/visudo || exit 1
 
     touch ${FLAG_DIR}/sudo-on
 }
@@ -219,9 +159,9 @@ vanilla-sudo () {
 
     [ ! -f ${BIN_PATH}/su-${VN_SUDO_SUF} ] && echo -e "${C_RED}ERROR: Not set up${C_RESET}" >&2 && exit 1
 
-    ln -sfT ${BIN_PATH}/su-${VN_SUDO_SUF} ${BIN_PATH}/su || exit 1
-    ln -sfT ${BIN_PATH}/sudo-${VN_SUDO_SUF} ${BIN_PATH}/sudo || exit 1
-    ln -sfT ${BIN_PATH}/visudo-${VN_SUDO_SUF} ${BIN_PATH}/visudo || exit 1
+    cp -p ${BIN_PATH}/su-${VN_SUDO_SUF} ${BIN_PATH}/su || exit 1
+    cp -p ${BIN_PATH}/sudo-${VN_SUDO_SUF} ${BIN_PATH}/sudo || exit 1
+    cp -p ${BIN_PATH}/visudo-${VN_SUDO_SUF} ${BIN_PATH}/visudo || exit 1
 
     rm ${FLAG_DIR}/sudo-on
 
@@ -231,21 +171,18 @@ vanilla-sudo () {
 setup-sudo () {
     echo SETUP-SUDO
 
+    [ -f ${BIN_PATH}/su-${VN_SUDO_SUF} ] && echo -e "${C_RED}ERROR: Already set up${C_RESET}" >&2 && exit 1
     pacman -Qi sudo-rs &> /dev/null || { echo "sudo-rs not installed"; exit 0; }
 
-    # add suffix to vanilla su + sudo + visudo
-    cp -p ${BIN_PATH}/su ${BIN_PATH}/su-${VN_SUDO_SUF}
-    cp -p ${BIN_PATH}/sudo ${BIN_PATH}/sudo-${VN_SUDO_SUF}
-    cp -p ${BIN_PATH}/visudo ${BIN_PATH}/visudo-${VN_SUDO_SUF}
-
-    # link su + sudo + visudo to vanilla
-    ln -sf ${BIN_PATH}/su-${VN_SUDO_SUF} ${BIN_PATH}/su
-    ln -sf ${BIN_PATH}/sudo-${VN_SUDO_SUF} ${BIN_PATH}/sudo
-    ln -sf ${BIN_PATH}/visudo-${VN_SUDO_SUF} ${BIN_PATH}/visudo
+    cp -p ${BIN_PATH}/su ${BIN_PATH}/su-${VN_SUDO_SUF} || exit 1
+    cp -p ${BIN_PATH}/sudo ${BIN_PATH}/sudo-${VN_SUDO_SUF} || exit 1
+    cp -p ${BIN_PATH}/visudo ${BIN_PATH}/visudo-${VN_SUDO_SUF} || exit 1
 
     touch ${FLAG_DIR}/sudo-setup
 
     [ -f ${FLAG_DIR}/sudo-on ] && rust-sudo
+
+    exit 0
 }
 
 remove-sudo () {
@@ -253,9 +190,9 @@ remove-sudo () {
 
     [ ! -f ${BIN_PATH}/su-${VN_SUDO_SUF} ] && echo -e "${C_RED}ERROR: Not set up${C_RESET}" >&2 && exit 1
 
-    cp -p --remove-destination ${BIN_PATH}/su-${VN_SUDO_SUF} ${BIN_PATH}/su || exit 1
-    cp -p --remove-destination ${BIN_PATH}/sudo-${VN_SUDO_SUF} ${BIN_PATH}/sudo || exit 1
-    cp -p --remove-destination ${BIN_PATH}/visudo-${VN_SUDO_SUF} ${BIN_PATH}/visudo || exit 1
+    cp -p ${BIN_PATH}/su-${VN_SUDO_SUF} ${BIN_PATH}/su || exit 1
+    cp -p ${BIN_PATH}/sudo-${VN_SUDO_SUF} ${BIN_PATH}/sudo || exit 1
+    cp -p ${BIN_PATH}/visudo-${VN_SUDO_SUF} ${BIN_PATH}/visudo || exit 1
 
     rm ${BIN_PATH}/su-${VN_SUDO_SUF} || exit 1
     rm ${BIN_PATH}/sudo-${VN_SUDO_SUF} || exit 1
@@ -286,7 +223,7 @@ post-transaction-sudo () {
 [ -z "$1" ] && echo "No arguments" >&2 && exit 0
 if declare -f "$1" > /dev/null
 then
-    [ $(/usr/bin/id -u) -ne 0 ] && echo -e "${C_RED}ERROR: You cannot run this unless you are root${C_RESET}" >&2 && exit 1
+    [ "$(/usr/bin/id -u)" -ne 0 ] && echo -e "${C_RED}ERROR: You cannot run this unless you are root${C_RESET}" >&2 && exit 1
     "$@"
 else
     echo "'$1' is not a known function name" >&2
